//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManiacEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class KeyBindDefaults : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyBindDefaults defaultInstance = ((KeyBindDefaults)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyBindDefaults())));
        
        public static KeyBindDefaults Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+F1</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NudgeFaster {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NudgeFaster"]));
            }
            set {
                this["NudgeFaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+F2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ScrollLock {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ScrollLock"]));
            }
            set {
                this["ScrollLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+F3</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ScrollLockTypeSwitch {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ScrollLockTypeSwitch"]));
            }
            set {
                this["ScrollLockTypeSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+X</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Cut {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Cut"]));
            }
            set {
                this["Cut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+C</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Copy {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Copy"]));
            }
            set {
                this["Copy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+V</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Paste {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Paste"]));
            }
            set {
                this["Paste"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Del</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Delete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Delete"]));
            }
            set {
                this["Delete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+D</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Duplicate {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Duplicate"]));
            }
            set {
                this["Duplicate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+A</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SelectAll {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SelectAll"]));
            }
            set {
                this["SelectAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+Z</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Undo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Undo"]));
            }
            set {
                this["Undo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+Y</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Redo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Redo"]));
            }
            set {
                this["Redo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+N</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection New {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["New"]));
            }
            set {
                this["New"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+O</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Open {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Open"]));
            }
            set {
                this["Open"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+Alt+O</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OpenDataDir {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OpenDataDir"]));
            }
            set {
                this["OpenDataDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+S</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection _Save {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_Save"]));
            }
            set {
                this["_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+Alt+S</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SaveAs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SaveAs"]));
            }
            set {
                this["SaveAs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+NumPad0</string>\r\n  <string>Ctrl+0</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResetZoomLevel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResetZoomLevel"]));
            }
            set {
                this["ResetZoomLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+U</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UnloadScene {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UnloadScene"]));
            }
            set {
                this["UnloadScene"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+1</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShowPathA {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShowPathA"]));
            }
            set {
                this["ShowPathA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShowPathB {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShowPathB"]));
            }
            set {
                this["ShowPathB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>None</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BackupNormal {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BackupNormal"]));
            }
            set {
                this["BackupNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>None</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BackupStageConfig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BackupStageConfig"]));
            }
            set {
                this["BackupStageConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>None</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Recover {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Recover"]));
            }
            set {
                this["Recover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+R</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RunScene {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RunScene"]));
            }
            set {
                this["RunScene"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>F5</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RefreshResources {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RefreshResources"]));
            }
            set {
                this["RefreshResources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+G</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShowGrid {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShowGrid"]));
            }
            set {
                this["ShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Shift+3</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShowTileID {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShowTileID"]));
            }
            set {
                this["ShowTileID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>M</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FlipH {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlipH"]));
            }
            set {
                this["FlipH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>F</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FlipV {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlipV"]));
            }
            set {
                this["FlipV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ShiftKey</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FlipVTiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlipVTiles"]));
            }
            set {
                this["FlipVTiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ControlKey</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FlipHTiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlipHTiles"]));
            }
            set {
                this["FlipHTiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+M</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FlipHIndv {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlipHIndv"]));
            }
            set {
                this["FlipHIndv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+F</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FlipVIndv {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlipVIndv"]));
            }
            set {
                this["FlipVIndv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>F3</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StatusBoxToggle {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StatusBoxToggle"]));
            }
            set {
                this["StatusBoxToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+Shift+V</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PasteToChunk {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PasteToChunk"]));
            }
            set {
                this["PasteToChunk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>None</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ForceOpenOnStartup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ForceOpenOnStartup"]));
            }
            set {
                this["ForceOpenOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>None</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DeveloperInterface {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DeveloperInterface"]));
            }
            set {
                this["DeveloperInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>None</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CopyAirTiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CopyAirTiles"]));
            }
            set {
                this["CopyAirTiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>None</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PointerTooltipToggle {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PointerTooltipToggle"]));
            }
            set {
                this["PointerTooltipToggle"] = value;
            }
        }
    }
}
