//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManiacEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManiacEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Acetone]
        ///filter
        ///interval
        ///intervalOffset
        ///duration
        ///
        ///[ActClear]
        ///filter
        ///
        ///[AIZEncoreTutorial]
        ///filter
        ///
        ///[AIZEggRobo]
        ///filter
        ///direction
        ///oscillate
        ///angle
        ///forKnux
        ///
        ///[AIZKingClaw]
        ///filter
        ///
        ///[AIZRockPile]
        ///filter
        ///size
        ///smashTop
        ///smashSides
        ///onlyKnux
        ///onlyMighty
        ///
        ///[AIZSetup]
        ///filter
        ///
        ///[AIZTornado]
        ///filter
        ///
        ///[AIZTornadoPath]
        ///filter
        ///type
        ///targetSpeed
        ///timer
        ///easeToSpeed
        ///
        ///[AmoebaDroid]
        ///filter
        ///type
        ///
        ///[AnimalHBH]
        ///filter
        ///type
        ///
        ///[Animals]
        ///filter
        ///type
        ///behaviour
        ///
        ///[Announcer]
        ///filter
        ///
        ///[APICa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string attributes {
            get {
                return ResourceManager.GetString("attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorMonitor {
            get {
                object obj = ResourceManager.GetObject("ErrorMonitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorStatic2 {
            get {
                object obj = ResourceManager.GetObject("ErrorStatic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoStatic2 {
            get {
                object obj = ResourceManager.GetObject("InfoStatic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff3\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset2 Symbol;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\froman\fprq2\fcharset0 Liberation Serif{\*\falt Times New Roman};}{\f4\fswiss\fprq2\fcharset0 Liberation Sans{\*\falt Arial};}{\f5\froman\fprq2\fcharset0 Segoe UI;}{\f6\fnil\fprq2\fcharset0 Microsoft YaHei;}{\f7\fnil\fprq2\fcharset0 Lucida Sans;}{\f8\fswiss\fprq0\fcharset128 Lucida Sans;}}
        ///{\colortbl;\red0\green0\blue0;\red0\green0\blue255;\red0\g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LayerManagerWarning {
            get {
                return ResourceManager.GetString("LayerManagerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff3\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset2 Symbol;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\froman\fprq2\fcharset0 Liberation Serif{\*\falt Times New Roman};}{\f4\fswiss\fprq2\fcharset0 Liberation Sans{\*\falt Arial};}{\f5\froman\fprq2\fcharset0 Segoe UI;}{\f6\fnil\fprq2\fcharset0 Microsoft YaHei;}{\f7\fnil\fprq2\fcharset0 Lucida Sans;}{\f8\fswiss\fprq0\fcharset128 Lucida Sans;}}
        ///{\colortbl;\red0\green0\blue0;\red0\green0\blue255;\red0\g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LayerManagerWarningDarkTheme {
            get {
                return ResourceManager.GetString("LayerManagerWarningDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring
        ///Player
        ///Platform
        ///TimeAttackGate
        ///Spikes
        ///ItemBox
        ///Bridge
        ///TeeterTotter
        ///HUD
        ///Music
        ///BoundsMarker
        ///TitleCard
        ///CorkscrewPath
        ///BGSwitch
        ///ForceSpin
        ///UIControl
        ///SignPost
        ///UFO_Ring
        ///UFO_Sphere
        ///UFO_Player
        ///UFO_ItemBox
        ///UFO_Springboard
        ///Decoration
        ///WaterGush
        ///BreakBar
        ///InvisibleBlock
        ///ForceUnstick
        ///BreakableWall
        ///CollapsingPlatform
        ///PlaneSwitch
        ///ChemicalPool
        ///Newtron
        ///Chopper
        ///TippingPlatform
        ///Spiny
        ///OneWayDoor
        ///Syringe
        ///StickyPlatform
        ///TwistedTubes
        ///ShopWindow
        ///DirectorChair
        ///TVVan
        ///FilmProjector
        ///Rockem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string objectRenderList {
            get {
                return ResourceManager.GetString("objectRenderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetone
        ///ActClear
        ///AIZEggRobo
        ///AIZEncoreTutorial
        ///AIZKingClaw
        ///AIZRockPile
        ///AIZSetup
        ///AIZTornado
        ///AIZTornadoPath
        ///AmoebaDroid
        ///AnimalHBH
        ///Animals
        ///Announcer
        ///APICallback
        ///Aquis
        ///Armadiloid
        ///BadnikHelpers
        ///Ball
        ///BallCannon
        ///BallHog
        ///BarStool
        ///Batbot
        ///Batbrain
        ///Beanstalk
        ///BGSwitch
        ///BigSqueeze
        ///BladePole
        ///Blank Object
        ///Blaster
        ///Blastoid
        ///Bloominator
        ///Bomb
        ///BouncePlant
        ///BoundsMarker
        ///BreakableWall
        ///BreakBar
        ///BSS_Collectable
        ///BSS_Collected
        ///BSS_Horizon
        ///BSS_HUD
        ///BSS_Message
        ///BSS_Palette
        ///BSS_Player
        ///BSS_Setup
        ///B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string objects {
            get {
                return ResourceManager.GetString("objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang2057{\fonttbl{\f0\fswiss\fprq2\fcharset0 Segoe UI;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red255\green0\blue0;}
        ///\viewkind4\uc1\pard\qc\f0\fs18 This feature is to be used \cf1\b with caution\cf0\b0 .\par
        ///\pard It will make changes to the \i StageConfig.bin\i0  file (if checked below) which belongs to the Scene you are currently editing. Some Objects will require you to import sounds, or make other changes; but those are not automatically handled...\par
        ///\pard\qc\b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectWarning {
            get {
                return ResourceManager.GetString("ObjectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff3\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset2 Symbol;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\froman\fprq2\fcharset0 Liberation Serif{\*\falt Times New Roman};}{\f4\fswiss\fprq2\fcharset0 Liberation Sans{\*\falt Arial};}{\f5\froman\fprq2\fcharset0 Segoe UI;}{\f6\fnil\fprq2\fcharset0 Microsoft YaHei;}{\f7\fnil\fprq2\fcharset0 Lucida Sans;}{\f8\fswiss\fprq0\fcharset128 Lucida Sans;}}
        ///{\colortbl;\red0\green0\blue0;\red0\green0\blue255;\red0\g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectWarningDarkTheme {
            get {
                return ResourceManager.GetString("ObjectWarningDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream OhNo {
            get {
                return ResourceManager.GetStream("OhNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RefreshStatic2 {
            get {
                object obj = ResourceManager.GetObject("RefreshStatic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ScoreTotal {
            get {
                return ResourceManager.GetStream("ScoreTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang2057{\fonttbl{\f0\fswiss\fprq2\fcharset0 Segoe UI;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red255\green0\blue0;}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\qc\f0\fs18 This feature is \cf1\b highly experimental\cf0\b0 .\par
        ///\pard It will make changes to the \i StageConfig.bin\i0  file which belongs to the Scene you are currently editing, in order to make the Sounds you select available for use. But actually getting those sounds to play...\par
        ///\pard\q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SoundWarning {
            get {
                return ResourceManager.GetString("SoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff3\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset2 Symbol;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\froman\fprq2\fcharset0 Liberation Serif{\*\falt Times New Roman};}{\f4\fswiss\fprq2\fcharset0 Liberation Sans{\*\falt Arial};}{\f5\froman\fprq2\fcharset0 Segoe UI;}{\f6\fnil\fprq2\fcharset0 Microsoft YaHei;}{\f7\fnil\fprq2\fcharset0 Lucida Sans;}{\f8\fswiss\fprq0\fcharset128 Lucida Sans;}}
        ///{\colortbl;\red0\green0\blue0;\red0\green0\blue255;\red0\g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SoundWarningDarkTheme {
            get {
                return ResourceManager.GetString("SoundWarningDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WarningMonitor {
            get {
                object obj = ResourceManager.GetObject("WarningMonitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WarningStatic2 {
            get {
                object obj = ResourceManager.GetObject("WarningStatic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
