//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TileManiacWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class KeyBinds : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyBinds defaultInstance = ((KeyBinds)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyBinds())));
        
        public static KeyBinds Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+N</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NewInstance {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NewInstance"]));
            }
            set {
                this["NewInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+O</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Open {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Open"]));
            }
            set {
                this["Open"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+S</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection _Save {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_Save"]));
            }
            set {
                this["_Save"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+Alt+S</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SaveAs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SaveAs"]));
            }
            set {
                this["SaveAs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+Alt+U</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SaveAsUncompressed {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SaveAsUncompressed"]));
            }
            set {
                this["SaveAsUncompressed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+U</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection _SaveUncompressed {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_SaveUncompressed"]));
            }
            set {
                this["_SaveUncompressed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection backupConfig {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["backupConfig"]));
            }
            set {
                this["backupConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection backupImage {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["backupImage"]));
            }
            set {
                this["backupImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ImportFromOlderRSDK {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImportFromOlderRSDK"]));
            }
            set {
                this["ImportFromOlderRSDK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OpenSingleColMask {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OpenSingleColMask"]));
            }
            set {
                this["OpenSingleColMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ExportColMask {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExportColMask"]));
            }
            set {
                this["ExportColMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+C</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Copy {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Copy"]));
            }
            set {
                this["Copy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+V</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Paste {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Paste"]));
            }
            set {
                this["Paste"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+Alt+V</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PastetoOther {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PastetoOther"]));
            }
            set {
                this["PastetoOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+M</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MirrorMode {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MirrorMode"]));
            }
            set {
                this["MirrorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RestorePathA {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RestorePathA"]));
            }
            set {
                this["RestorePathA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RestorePathB {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RestorePathB"]));
            }
            set {
                this["RestorePathB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RestorePaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RestorePaths"]));
            }
            set {
                this["RestorePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+B</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShowPathB {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShowPathB"]));
            }
            set {
                this["ShowPathB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+G</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShowGrid {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShowGrid"]));
            }
            set {
                this["ShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ClassicMode {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ClassicMode"]));
            }
            set {
                this["ClassicMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SplitFile {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SplitFile"]));
            }
            set {
                this["SplitFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FlipTileH {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlipTileH"]));
            }
            set {
                this["FlipTileH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FlipTileV {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlipTileV"]));
            }
            set {
                this["FlipTileV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection HomeFolderOpen {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HomeFolderOpen"]));
            }
            set {
                this["HomeFolderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection About {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["About"]));
            }
            set {
                this["About"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Settings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Settings"]));
            }
            set {
                this["Settings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ctrl+T</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection WindowAlwaysOnTop {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WindowAlwaysOnTop"]));
            }
            set {
                this["WindowAlwaysOnTop"] = value;
            }
        }
    }
}
